name: EWI
favicon: null
layout_spectrum: 0.25145
typography_spectrum: 0.75048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#33342f'
    - '#58656e'
    - '#a6725d'
    - '#eeb9ad'
  brandStrength: 0.5
  lightness: 0.6380610240157694
  saturation: 0.24756184918805957
  rhythmicContrast: 0.8160983615089208
purpose: []
